export GPG_TTY=$(tty)

alias brewupd="brew update"
alias brewupg="brew upgrade"
alias brewinst="brew install"
alias brewuninst="brew uninstall"
alias brewall="brew update && brew upgrade"

alias aptupd="sudo apt update"
alias aptupg="sudo apt full-upgrade"
alias aptinst="sudo apt install"
alias aptauto="sudo apt autoremove"
alias aptall="sudo apt update && sudo apt full-upgrade && sudo apt autoremove"

alias gini="git init"
alias gadd="git add"
alias gcom="git commit"
alias gstat="git status"
alias gdiff="git diff"
alias gcheck="git checkout"
alias gft="git fetch"
alias gpull="git pull"
alias gsubadd="git submodule add"
alias gsubpull="git submodule foreach git pull origin main"
alias gpush="git push"
alias greb="git rebase"
alias gres="git reset"
alias glog="git log"
alias grmt="git remote"

alias compinst="composer install"
alias compupd="composer update"
alias compreq="composer require"
alias comprem="composer remove"

export THEOS=~/theos
alias theos=~/theos/bin/nic.pl
alias install="make clean package install -j"
alias installr="THEOS_PACKAGE_SCHEME=rootless make clean package install -j"
alias final="THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1 make clean package -j && open packages/"
alias finalr="FINALPACKAGE=1 make clean package -j && open packages/"
alias easy="GO_EASY_ON_ME=1 make clean package install -j"
alias easyr="THEOS_PACKAGE_SCHEME=rootless GO_EASY_ON_ME=1 make clean package install -j"
alias package="make clean package -j && open packages/"
alias packager="THEOS_PACKAGE_SCHEME=rootless make clean package -j && open packages/"
export THEOS_DEVICE_IP=127.0.0.1
export THEOS_DEVICE_PORT=2222
